# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('image_1', models.ImageField(blank=True, upload_to='information/information/%Y/%m/%d')),
                ('image_2', models.ImageField(blank=True, upload_to='information/information/%Y/%m/%d')),
                ('image_3', models.ImageField(blank=True, upload_to='information/information/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
