# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Quiz',
        ),
    ]
