# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170804_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.CharField(default='anonymous', max_length=50),
            preserve_default=False,
        ),
    ]
